services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: dsindres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../subject/customer:/csv_data 
    restart: always

volumes:
  db_data:
